# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3357a8926f58127e37106769cd261b406945a0b7f157d85eac0f9274762f87df189d911a17f9479a5cca169ac694174c3d51fab412722f60f300a898a4c4139e

test:
  secret_key_base: 7cc6caea533be5b8a90e5e72bf0168fc548dbcb6cb28f75f22c69e02cb2b0fd6faecccd1b36ba168dc71c316d5e043ce586ad5539e115e39972151fe64298d41

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
